[package]
name = "store"
version = "0.2.0"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]

[dependencies]
aws-sdk-rust = "0.1.42"
dotenv = "0.10.1"
hyper = "0.10"
rust-crypto = "0.2.36"
url = "*"
